name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # ESLint doesn't support Node 12.10 anymore. Test on the oldest available
                # node that our tools support.
                node: ["12.22", "12", "14", "16"]
        name: Node ${{ matrix.node }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: Upgrade npm
              run: npm i -g npm@latest
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test:full
              env:
                  # For pull requests, this gets handled by the visual-regression workflow.
                  # For other test runs, skip so we don't have to go build the regression screenshots.
                  SKIP_VISUAL_TEST: true
            - name: Lint
              run: npm run lint
            - name: Circular dependency check
              uses: gerrit0/circular-dependency-check@v1
              with:
                  entry: dist/index.js
